### ISSUE TITLE
Cannot run without .licensee.json file

### ISSUE THREAD

**Issue by RichardLitt** [jslicense/licensee.js#13]
```sh
~/random-project $ licensee
Cannot read ~/random-project/.licensee.json
```

Would be ideal to automatically create this file with `licensee --init`, or to specify in usage that it must be manually created first.

**Comment by kemitchell** [comment]
You can run without a configuration file using `--license EXPRESSION` and `--whitelist LIST`. See `licensee --help`.

I agree that at a very minimum, the error message should do more to help. I'll push a change for that shortly.

`--init` isn't a bad idea, either, though we'd have to come up with a default.

**Comment by RichardLitt** [comment]
Thank you.
