### ISSUE TITLE
Option to skip dev dependencies

### ISSUE THREAD

**Issue by ljharb** [jslicense/licensee.js#18]
I'm primarily concerned with the licenses I distribute, not the licenses of the dev tools I use.

Could there be an option like `--production` that skipped devDeps (but checked deps, peerDeps, bundledDeps, etc)?

**Comment by kemitchell** [comment]
I've often thought of this as well.

The package we currently use to recurse node_modules does not distinguish devDependencies. Do you know of a package that does?

In the meantime, a stopgap for many use cases:

```
mv node_modules node_modules.bak
npm i --offline
licensee
rm -rf node_modules
mv node_modules.bak node_modules
```

You may want something like this in npm or CI scripts.

**Comment by kemitchell** [comment]
Sorry, the npm install line should have read:

npm install --offline --production

**Comment by ljharb** [comment]
I would assume you recurse node_modules by parsing `npm ls --json`, in which case you could use `npm ls --json --production` - it didn't occur to me to use a package for it.

**Comment by kemitchell** [comment]
I've just had a look at npm CLI. The relevant file there is `/lib/ls.js`.

The CLI uses `read-package-tree`, just like `licensee`. It then runs npm CLI-specific code in `lib/install/mutate-into-logical-tree` to turn the tree from disk into a tree reflecting the dependency hierarchy.

I'm not sure that shelling out to npm isn't the right idea. The `dependencies`-versus-`devDependencies` distinction is an npm think, not a Node.js thing. I like the idea of supporting folks who have a project with `node_modules`, say, checked into Git, but no npm. But I imagine that's a relatively small group of people.

**Comment by ljharb** [comment]
The "license" field is an npm thing as well.

**Comment by kemitchell** [comment]
Aye.

**Comment by ljharb** [comment]
At any rate, you can directly depend on `npm` which would avoid relying on it being installed - would that suffice?

**Comment by kemitchell** [comment]
Looks like `npm ls --json` _runs_ `read-package-tree`, but doesn't output file system path information. So we'd need to continue to running `read-package-tree`, shell out to `npm` at the same time, and put the two together.

Would you happen to be aware of any npm CLI breakage on `--json` output?

**Comment by kemitchell** [comment]
I think putting npm in dependencies would make this a massive, redundant install. I'd like to avoid that.

**Comment by kemitchell** [comment]
I'm going to try to implement. The plan will be to shell out, and bail if the JSON we receive is not the JSON we expected.

**Comment by kemitchell** [comment]
@ljharb, talk you into reviewing the PR?

**Comment by ljharb** [comment]
Fair enough on depending on it.

`--json` definitely has issues with some commands; generally I've found it either works as expected, or doesn't alter the format.

Always happy to review!
