### ISSUE TITLE
licenserc support

### ISSUE THREAD

**Issue by kemitchell** [jslicense/licensee.js#2]
- [ ] differentiate uses
- [ ] load `.licenserc` by default

**Comment by rprieto** [comment]
I think this would be very useful.

The `rc` npm package can make this easy, since it supports many formats (json, ini) and many default paths. For example it would even allow having a `.licenserc` in your home directory that applies to all projects.

**Comment by ChristianMurphy** [comment]
https://github.com/davidtheclark/cosmiconfig may be able to help

**Comment by kemitchell** [comment]
I don't expect this is going anywhere for the foreseeable future. @rprieto, you might like to link in a `.licensee` file with `ln`. I'm not really interested in complicating the package with support for many data formats. But if you'd really like a `$HOME/.licensee`, and are willing to think through the semantics and UI of how that might interact with `$CDW/.licensee`, by all means fork, get it working, and send a PR.
