### ISSUE TITLE
Licenses key

### ISSUE THREAD

**Issue by ravjsdev** [jslicense/licensee.js#20]
Hi
Licensee currently only checks the `license` key and ignores the old npm format `licenses` key - can you update licensee so that it at least makes any information under a `licenses` key available to anyone using licensee - you don't need to do anything with it but if its available it avoids me having to re-read `package.json` files to check if that key exists
many thanks

**Comment by kemitchell** [comment]
@ravjsdev Thanks for creating an issue on this before sending a PR. I don't think I'd take a PR to have `licensee` do this in my own branch. That's clearly a problem that the packages should fix, by moving to `license`. It's been many years since npm spec'd and began validating `license`.
