### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by ravjsdev** [jslicense/licensee.js#21]
Hi @kemitchell can you update your dependencies - im currently getting 

├─┬ licensee@4.5.0
│ └─┬ read-package-tree@5.1.6
│   └─┬ read-package-json@2.0.12
│     └─┬ normalize-package-data@2.4.0
│       └─┬ validate-npm-package-license@3.0.1
│         └─┬ spdx-correct@1.0.2
│           └── spdx-license-ids@1.2.2
└─┬ spdx-expression-parse@2.0.2
  └── spdx-license-ids@2.0.1

licensee is using the old `spdx-license-ids` - a few of the module dependencies in the tree need updating to fix this - can you also bump the `licensee` version when you've updated this.

thanks

**Comment by kemitchell** [comment]
Closed by 5.0.0.

By the way, it's perfectly normal to send PRs with updated dependencies, especially with CI to show that all tests still pass!
