### ISSUE TITLE
Wildcards?

### ISSUE THREAD

**Issue by ljharb** [jslicense/licensee.js#27]
We have lots of internal packages under either a scope, or a common name prefix. It would be great to be able to whitelist "airbnb-*", for example, without having to manually add each new one to the list.

**Comment by kemitchell** [comment]
Valid use case. Valid request.

I might group this with the idea of being able to configure `licensee` to ignore packages that you yourself wrote.

Perhaps an additional configuration file property, like:

```json
{
"rule": "(MIT OR BSD-2-Clause)",
"whitelist": {
},
"ignore": [
{"prefix": "airbnb-*},
{"scope":"@airbnb"},
{"author": "Jordan Harband"}
]
}
```

`prefix` would do `package.name.startsWith(x)`. `scope` would do `package.scope === x`. `author` would do `package.author.toLowerCase().includes(x)`.
