### ISSUE TITLE
deduping

### ISSUE THREAD

**Issue by ljharb** [jslicense/licensee.js#28]
I'm seeing multiple entries in the list - presumably when a dependency is duplicated in the graph.

It'd be ideal if when the package name and license data are the same, they could all be collapsed to a single entry (with a semver range covering the ones that are the same).

**Comment by kemitchell** [comment]
IIRC, the place to add a `array.includes(element)` check is here: https://github.com/jslicense/licensee.js/blob/8c6b68f2fd82d3cbcdfed8714475900091ba4d02/index.js#L151
