### ISSUE TITLE
I can't whitelist invalid SPDX identifiers

### ISSUE THREAD

**Issue by ljharb** [jslicense/licensee.js#29]
Whether or not a package is using a valid identifier or not, I'd like to be able to whitelist it's license type. I have multiple packages with "MIT/X11", and since that's basically MIT, i'd like to allow those - but licensee errors out.

**Comment by kemitchell** [comment]
I feel this pain, too. But I'm really hesitant to support the feature.

I believe there's an old PR on `spdx-expression-parse` to allow "loose" parsing with invalid identifiers. But even if we supported loose parsing all the way up to `spdx-satisfies`, I'm not sure it would be a good idea.  SPDX identifiers resolve to specific terms. Invalid identifiers do not.

**Comment by ljharb** [comment]
I agree that SPDX tools themselves shouldn't allow it; I'm only asking for it to be supported inside licensee's `whitelist` field.

**Comment by kemitchell** [comment]
I don't want `licensee` to end up encouraging invalid `package.json` `license` values, per the `package.json` spec. If the terms aren't SPDX-standardized, the right answers are `UNLICENSED` or `SEE LICENSE IN LICENSE.md`.

The `MIT/X11` damage is already done, I know. In fact, I'd bet four shiny quarters a certain Master Halliday's work stands prominently in your stack. But #32 feels like a cleaner way to deal with those old packages. Here's what `license` _should_ be in `package.json`...

**Comment by ljharb** [comment]
A “resolutions” feature seems totally great.

**Comment by kemitchell** [comment]
@ljharb I'm closing this as #wontfix, but please don't take that the wrong way. Let's take it to #32. That seems like the best chance to row one boat in one direction.
