### ISSUE TITLE
Indicate top-level dep, or transitive via who

### ISSUE THREAD

**Issue by ljharb** [jslicense/licensee.js#30]
It'd be awesome if the report indicated whether a dep was top-level, or if not, which packages caused it to be included.

**Comment by kemitchell** [comment]
@ljharb I suspect `read-package-tree` includes that information in records. Perhaps "encoded" in the module's path.

The place to bring that in is probably https://github.com/jslicense/licensee.js/blob/8c6b68f2fd82d3cbcdfed8714475900091ba4d02/index.js#L175

The place to print it out is probably https://github.com/jslicense/licensee.js/blob/8c6b68f2fd82d3cbcdfed8714475900091ba4d02/licensee#L143

I'm a bit slammed. Feel free to send a PR. `npm run style` lints.

**Comment by kemitchell** [comment]
Could we just print path?

**Comment by ljharb** [comment]
Dep hoisting makes the path unhelpful.

**Comment by kemitchell** [comment]
Yeah, this is going to get nasty.

If you'd like to send a PR, by all means do. But this isn't something I'm going to tackle.
