### ISSUE TITLE
If a package is whitelisted, also whitelist all of its transitive deps

### ISSUE THREAD

**Issue by ljharb** [jslicense/licensee.js#31]
Related to #30, if I whitelist a package, i'd love a way to also auto-whitelist anything it's bringing in.

**Comment by kemitchell** [comment]
I'm not sure what's right here.

On the one hand, turning a blind eye to sub-deps is dangerous. That is exactly where licensing issues take root.

On the other hand, especially with in-house packages, I want to avoid the complexity of, say, recursive .licensee.json files. It's quick and easy to recurse all of `node_modules`, even when `node_modules` is huge. Short circuiting the top-level `licensee` analysis is actually more complicated, I think.  Links.  Cycles. Dupes.  Ouch.

**Comment by ljharb** [comment]
Fair enough; it's more that we have, for example, an internal package that's both a runtime *and* a dev dep - and all of its transitive deps that are runtime are fine. So, rather than manually whitelisting each dev-only module, i'd rather just delegate that trust to the internal repo.

**Comment by kemitchell** [comment]
@ljharb `--production`?

**Comment by ljharb** [comment]
Because this package is both, it’s listed in “dependencies”, so the transitive dev-only deps can’t be filtered out (I’m always using the production flag because the licenses of non distributed dev deps aren’t a concern). Obviously we should split it into two, but in the meantime I’m hoping for a manageable solution.

**Comment by kemitchell** [comment]
> Obviously we should split it into two, but in the meantime I’m hoping for a manageable solution.

Your pain here is completely valid. I want to validate it, not dismiss it. Not at all.

At the same time, from my experience, ignoring sub-deps would be both a technical morass and a legal footgun.

If you fork to implement it, I will absolutely do my best to keep it easy to flow patches downstream. But I don't want to mislead you about my time or attention. It's not something I'll contribute to directly, and I'm not enthused about its complexity cost.

> (I’m always using the production flag because the licenses of non distributed dev deps aren’t a concern)

Mea culpa: https://licensezero.com/licenses/parity
