### ISSUE TITLE
Support for `licenses` property

### ISSUE THREAD

**Issue by mikeal** [jslicense/licensee.js#4]
Ran into this on with `corsify`.

```javascript
{"licenses": [
    {
      "type": "MIT",
      "url": "http://github.com/Raynos/corsify/raw/master/LICENSE"
    }
  ]
}
```

I didn't even know about this property and style of format but apparently it's in use :/

```
corsify@2.1.0 (Invalid license metadata)
```

**Comment by kemitchell** [comment]
I believe this is malformed, even under the ancient RubyGems / CommonJS convention. `npm` will warn about it. The `package.json` spec went to the current, string value years ago.

If you want to whitelist manually, you can do `--whitelist "corsify@2.1."`, or add to `.licensee.json`:

```json
{
  "license":"...",
  "whitelist": {
    "corsify":"2.1.0"
  }
}
```

Could also send him a patch.  Will definitely shorten the file.  Uber & co. have their own license tools written to the spec. They seem to take this kind of thing pretty seriously.

**Comment by mikeal** [comment]
So the only way to describe multiple licenses now is to use the single string syntax from SPDX?

How would someone describe a package is dual licensed where one license is custom? I'm not a fan of this approach but it is a question I got today.

**Comment by kemitchell** [comment]
The `package.json` spec is for an SPDX _expression_. Any single identifier is a valid expression. So are compound expressions: `(GPL-2.0 OR MIT)`, `(MIT AND CC-BY-3.0)`.

npmjs.com will also display compound expressions: https://www.npmjs.com/package/spdx-expression-parse.

[There is doc on package.json. With examples.](https://docs.npmjs.com/files/package.json#license)

**Comment by kemitchell** [comment]
SPDX expressions describe standard licenses. If you have a custom license, there is a `SEE LICENSE IN ____` npm magic value.

If you dual license under a standard license and a custom one, you have your choice of the magic value or just listing the standard license. There was much debate on this.
