### ISSUE TITLE
Please keep a changelog

### ISSUE THREAD

**Issue by jhabdas** [jslicense/licensee.js#40]
Help users understand what's changing.

**Comment by kemitchell** [comment]
@jhabdas This project writes good commit messages. You can tell at a glance what's changed from the log: https://github.com/jslicense/licensee.js/commits/master

**Comment by jhabdas** [comment]
I'll just leave this here: https://keepachangelog.com/en/1.0.0/

**Comment by kemitchell** [comment]
@jhabdas If you'd like a changelog, feel free to watch releases and send PRs.
