### ISSUE TITLE
Time to drop fs-access dependency?

### ISSUE THREAD

**Issue by ronkorving** [jslicense/licensee.js#42]
I assume everybody is getting the same warning as I am:

> npm WARN deprecated fs-access@2.0.0: This package is no longer relevant as Node.js 0.12 is unmaintained.

Node.js 0.12 is ancient, so maybe it's time to drop this dependency?

**Comment by ljharb** [comment]
Most of my personal packages support back to 0.6; I'd instead file an issue on fs-access to remove the unnecessary and unhelpful warning. 0.12 being unmaintained is irrelevant; what's relevant is that there's still people using it.

**Comment by kemitchell** [comment]
I personally support keeping compat as far back as possible. There’s a limit. I can’t say offhand what it is. But lots of folks working at companies need licensee more than they need to upgrade Node.

For the record: Upgrade Node.

**Comment by ronkorving** [comment]
Sure thing :) Thanks for clarifying.
