### ISSUE TITLE
add option/flag for all OSI approved license

### ISSUE THREAD

**Issue by evilebottnawi** [jslicense/licensee.js#44]
https://opensource.org/licenses/alphabetical, will be great allow to setup this as in config as in cli, thanks for good project.

 I can send a PR

**Comment by kemitchell** [comment]
jslicense also maintains https://github.com/jslicense/spdx-osi.json, but I'm not sure how useful `licensee ---osi` would be. I don't think I'd ever recommend that configuration to a client.

**Comment by evilebottnawi** [comment]
@kemitchell we want use this package for linting our licenses in project, we accept all OSI licenses, it is avoid for use writing long SPDX license expression

**Comment by kemitchell** [comment]
That’s probably I’ll-advised. But I’d take a patch. Compare #43, which I’ll likely merge today.

**Comment by evilebottnawi** [comment]
@kemitchell so how we can solve this?

**Comment by evilebottnawi** [comment]
friendly ping

**Comment by kemitchell** [comment]
See above. We’d review a patch.

You might just want to fork. There are changes coming in SPDX-satisfies that probably induce a rewrite of rules configuration in licenses.

**Comment by evilebottnawi** [comment]
@kemitchell maybe we can allow using `js` configuration? We can build SPDX OSI approved licenses.

**Comment by kemitchell** [comment]
Closed by #45.

**Comment by evilebottnawi** [comment]
Good work, thanks
