### ISSUE TITLE
Option to ignore missing peer dependencies

### ISSUE THREAD

**Issue by nzacca** [jslicense/licensee.js#48]
Hello!

We've recently updated to Angular 8 and we've come across a scenario where a dependency has not updated its dependency list to support the new version and is thus raising an expected peer dependency error. This causes a problem with licensee when `npm ls` is used to retrieve the production dependency list. As a result, our license check is failing in our build pipeline. We've disabled the license check as a temporary workaround.

This is the underlying error being raised by `npm ls --production`:
```
peer dep missing: @angular/core@>=6.0.0 <8.0.0, required by angular-in-memory-web-api@0.8.0
```

We have confirmed that, for our purposes, this is a safe upgrade as [we await the PR](https://github.com/angular/in-memory-web-api/pull/241) but were wondering if it would be possible to add a flag to ignore peer dependency errors. Right now, we are unable to get a list of actual license errors `--errors-only --production` since the task fails on the peer dependency errors and exits before parsing the json.

Something like:
```
licensee --production --errors-only --ignorePeerDepsErrors
```

There doesn't appear to be a flag on `npm ls` to ignore those errors, unfortunately. That would have been an easier fix.

I'm willing to attempt a PR if this sounds ok. Thoughts?

Thank you!

**Comment by ljharb** [comment]
When `npm ls` exits nonzero, your entire dep graph is invalid - that should be gating your entire CI anyways.

**Comment by nzacca** [comment]
@ljharb Understood. In this particular case though we want to let it through so that we can get an early start on the upgrade. We're relying on our tests to catch anything that is actually broken. That said, it might be useful to be able to see the list of license errors regardless of the missing peer dependencies.

**Comment by kemitchell** [comment]
@nzacca ideally, I think `licensee` would succeed if it can do its job, and fail only if it can't, independent of whether other tools succeed or fail.

However, `licensee` uses both `npm` and its dependency, `read-package-tree`, to recurse the package tree in `node_modules`. Reusing that code saves us a lot of work. But more importantly, it also ensures that `licensee` sees `node_modules` the same way `npm` does.

It's been a while since I looked at `read-package-tree`'s implementation. But I don't think it exposes options or other mechanisms to reliably skip peer dependencies.

**Comment by nzacca** [comment]
@kemitchell That makes sense. Thank you. I agree that the tool should be independent of other tools but in this case it's failing on an error produced by its dependency - even though it can succeed off of the output.

Just to clarify, I'm not asking to ignore peer dependencies in the graph; just ignore the error that occurs in the output from npm so that the output from licensee can produce something meaningful to the user. `npm ls` is producing a parseable json string but we never get to see it when `--production` is used and (expected) missing peer dependencies exist. :( It would be nice to exclude devDependencies and still see what dependencies fail the license criteria.

Thank you for your time! Appreciate you and @ljharb having the discussion.

**Comment by kemitchell** [comment]
@nzacca if you can implement in a PR, I will review. But I don't want to mislead you: This isn't something I expect I'll tackle myself.

**Comment by nzacca** [comment]
@kemitchell Sounds good. I don't mind giving it a go.
