### ISSUE TITLE
Add a "quiet" mode which only shows issues

### ISSUE THREAD

**Issue by swernerx** [jslicense/licensee.js#5]
Thanks for the amazing new module. Immentiately added it to one of our boilerplates. It would be nice though to have a new mode where we can just output the problematic packages in a compact format (no contributors, etc.).

Do you have something like this in mind, too?

**Comment by kemitchell** [comment]
@swernerx, looks like the party is at @janl's #8. Looking at something like `--errors` or perhaps `--errors-only`.
