### ISSUE TITLE
Support conjunction

### ISSUE THREAD

**Issue by brettz9** [jslicense/licensee.js#60]
I see parsed SPDX expressions with `conjunction` are excluded. I'd like to request support for expressions exclusively limited to `or` conjunctions. It would be nice to optionally support AND conjunctions as well if all of the AND items are present.

**Comment by kemitchell** [comment]
What semantics?

**Comment by brettz9** [comment]
If OR is used, treat it as approved if at least one of the alternatives is present.

**Comment by kemitchell** [comment]
Sketch this in a PR, perhaps just test cases to start?

**Comment by brettz9** [comment]
My apologies, I see conjunctions can be used, but it is just not for `licenses` whitelists. And for `licenses`, one can simply add additional licenses to the whitelist in that case. Thanks!
