### ISSUE TITLE
FR: Flexibility with the SPDX License List

### ISSUE THREAD

**Issue by mehdi-cit** [jslicense/licensee.js#7]
Hello and thank you for this neat module.
I'm not sure this is a good idea but consider being more flexible with the SPDX License Identifiers "parsing".
For instance, some modules have their license set as MIT/X11, meaning to allow for a dual license. In such case licensee could allow the module if the configuration specifies either MIT or X11.
As I said above, not sure this is a good idea as it doesn't follow the "general practices" but it could be made as an option in the licensee.json configuration file.
One more question, Does licensee only scan modules defined under "dependencies" in package.json or does it also scan modules defined under devDependencies ? 
Maybe the configuration should allow for specifying which alternative to go with.

**Comment by kemitchell** [comment]
Modules with `"license":"MIT/X11"` in `package.json` are out-of-[spec](https://docs.npmjs.com/files/package.json#license).  Publishers should be getting warnings about invalid license metadata.

Moreover, I don't think `MIT/X11` means what you think it means.  I'd suggest you have a quick read through the Wikipedia page on The MIT License, for the background.

`licensee` checks all the contents of `node_modules`, without reference to `package.json`.  If you install `devDependencies`, it will check those dependencies.  If you `npm install --production`, only regular `dependencies` will be in `node_modules`.
