### ISSUE TITLE
Support 'LicenseRef' license name when initializing the package.json with 'npm init' command

### ISSUE THREAD

**Issue by dd-jy** [jslicense/licensee.js#76]
Why cannot use 'LicenseRef' license name when initializing the package.json with 'npm init' command?

![image](https://user-images.githubusercontent.com/50347670/160727259-526e4c59-9621-4def-8cf4-586f229fcce2.png)

If users wants to add the proprietary license name in package.json, they may also want to add the license name to match the spdx license expression. Because it is easier to manage the license name of their package than using 'SEE LICENSE IN '.

What about changing to accept 'LicenseRef-' spdx license expression?

**Comment by kemitchell** [comment]
Licensee is a CLI tool for auditing dependency licenses. It's not part of npm CLI.

**Comment by dd-jy** [comment]
@kemitchell 
Actually, I requested this issue in npm-rfcs(https://github.com/npm/rfcs/discussions/563).
Then, can you tell me where I can post it?

**Comment by ljharb** [comment]
Does licensee support this kind of SPDX expression? If so, it’s an npm issue, but i assumed that if it did, npm would automatically support it.

**Comment by ljharb** [comment]
(or is licensee not what npm uses to validate spdx expressions? It’s certainly what it’ll use for `npm audit licenses`)

**Comment by dd-jy** [comment]
@kemitchell 
I searched the licensee code, and licensee only allows the spdx license list names (https://www.npmjs.com/package/spdx-osi).
In SPDX license expression, it also supports 'LicenseRef-' spdx license expression. So I request it to licensee.

**Comment by kemitchell** [comment]
> It’s certainly what it’ll use for `npm audit licenses`

Is that a future plan? I was not aware.

I see CLI is currently using `licensee` to audit their own deps:

https://github.com/npm/cli/blob/d8d374d23d34c17e22b52afc1cfb5247cc7c3e1d/package.json#L215=

But I don't see it in the CLI codebase otherwise.

**Comment by kemitchell** [comment]
@dd-jy: I don't have time to help you route your question. Please direct to the npm team if you have an issue with npm.

@ljharb: The `LicenseRef` concept is an obscure SPDX thing, and not one that either npm CLI or `licensee` should entertain, in my opinion. I'm sure there are old npm CLI issues where Forrest and I discussed, from way back when.

**Comment by ljharb** [comment]
In that case, sorry for the noise here, that's my bad.

@dd-jy you'd need to file an npm RFC to discuss changing it, but @kemitchell's opinion carries a lot of weight here.

**Comment by TristanWasTaken** [comment]
> [@ljharb](https://github.com/ljharb): The `LicenseRef` concept is an obscure SPDX thing, and not one that either npm CLI or `licensee` should entertain, in my opinion. I'm sure there are old npm CLI issues where Forrest and I discussed, from way back when.

@kemitchell sorry to necro this issue, but in my opinion it is way less obscure than npm's `See <license file>`, which is *not* supported by spdx and subsequently any tool that properly supports spdx (SBOM generators, license scanners, compliance dashboards, vulnerability management systems).
Sure, we can do with npm's current custom license solution with a sprinkle of never change a running system.
Still, if it says I have to pick an spdx identifier and it does, in fact, *not* support all official spdx identifiers, it should at the *very least* be documented everywhere it mentions spdx support.
