### ISSUE TITLE
Specify supported Node.js version in the manifest

### ISSUE THREAD

**Issue by ericcornelissen** [jslicense/licensee.js#84]
Relates to #55 

---

Suggestion to add [the `"engines"` field](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines) to the project's [`package.json`](https://github.com/jslicense/licensee.js/blob/9abd28fde91b5343a9b9322f6e5cb9547093febc/package.json) to make the supported Node.js versions explicit. This would allow users of licensee to be informed about (potential) incompatibility with their current Node.js version if they use the [`engine-strict`](https://docs.npmjs.com/cli/v9/using-npm/config#engine-strict) option.

Not sure what the preferred approach would be, but based on [the list of Node.js version tests](https://github.com/jslicense/licensee.js/blob/9abd28fde91b5343a9b9322f6e5cb9547093febc/.github/workflows/ci.yml#L8) some options include:

- Minimum only:
  - `"node": ">=12"`
  - `"node": "^12 | ^13 | ^14 | ^15 | ^16 | ^17 | >=18"`
- Minimum and maximum (would require a patch update to add support for a new Node.js version):
  - `"node": ">=12 <19"`
  - `"node": "^12 | ^13 | ^14 | ^15 | ^16 | ^17 | ^18"`

**Comment by ljharb** [comment]
Indeed, if this isn’t specified explicitly, the declared support is “everything that happened to work on the .0.0 version”

**Comment by ljharb** [comment]
Done in aaa9b26cecb1affae10a4511581c252a73a873cb
