### ISSUE TITLE
Comments in the .license.json file

### ISSUE THREAD

**Issue by tobysmith568** [jslicense/licensee.js#89]
Hey :)

Would you be open to the idea of parsing the `.licensee.json` file using something like [json5](https://www.npmjs.com/package/json5) so that the file can contain comments?

After having a brief look over the repository, it seems that it could perhaps be a drop-in replacement on [line 105 of /licensee](https://github.com/jslicense/licensee.js/blob/d44aa11e7fe4154b0eae160c98278801d12f0fa5/licensee#L105) with the only changes being:
- Adding an require statement `const JSON5 = require('json5');`
- Changing `JSON.parse(data)` to `JSON5.parse(data)`.

Thanks for your consideration

**Comment by kemitchell** [comment]
The lack of comments in JSON is truly annoying.

I'm not that familiar with JSON5. How much more does it bring in, beyond "JSON with comments"? I'd hate to see major-version breakages in Licensee because something happened down in the parser.

**Comment by kemitchell** [comment]
Hmm. Why not define a `licenses` script in `package.json` like `json5 < .licensee.json5 > .licensee.json && licensee`, then add `.licensee.json` to `.gitignore`?

**Comment by tobysmith568** [comment]
While I appreciate that this would work, it's not quite the seamless experience I was hoping to achieve.

Perhaps it's just me, but whenever I experiment with a new tool I usually have a "Does their JSON parser support comments?" thought process - and it's always a nice win when it does.

**Comment by kemitchell** [comment]
Licensee does just one thing, and tries to do it well. I'm personally motivated to keep maintaining for that mission, but not to chase the latest in plushness or polish.

If other want to do what Licensee does, but integrate into other systems or experiment with user experiences, the package also exports a module.

**Comment by ljharb** [comment]
Nothing should support json5, or any other format, until node natively supports it, even if it's better.
